### ISSUE TITLE
Error in loader. Cant run external in Linux

### ISSUE THREAD

**Issue by JRSV** [kmatheussen/k_cext#1]
I just found this object, which looks great and I want to give it a try, but PD 0.50.2 won't load it.
(Fedora 31).

the PD console prints out the following.

`k_cext v0.3.1, written by Kjetil S. Matheussen, k.s.matheussen@notam02.no
Windows-port by Olaf Matthes. Contributors: Thomas Grill and Tim Blechmann.
Compiling /tmp/pd-k_cext-d3ipCR.c
Error in loader!`

**Comment by kmatheussen** [comment]
What's the output of

ldd -r /tmp/pd-k_cext-d3ipCR.c.o

?

**Comment by kmatheussen** [comment]
And does

gcc -Wall -O2 /tmp/pd-k_cext-d3ipCR.c -o /tmp/pd-k_cext-d3ipCR.c.o -shared -fPIC

run?

**Comment by JRSV** [comment]
Hello and sorry for the biiig delay,
I have recently changed linux platforms and I am now based on DEBIAN, 
compiling the objects print out this:

`sudo make
cc -DPD -DUNIX -DICECAST -O2 -funroll-loops -fomit-frame-pointer -Wall -W -Wno-shadow -Wstrict-prototypes -Wno-unused -Wno-parentheses -Wno-switch -fPIC  -I../../src -DINCLUDEPATH=\""`pwd`"\" -DLINUXINCLUDE=\""../../src"\" -o k_cext.o -c k_cext.c
In file included from k_cext.c:111:
k_cext_funchandler.c: In function ‘k_cext_addintfunc’:
k_cext_funchandler.c:69:37: warning: cast between incompatible function types from ‘void (*)(struct k_cext *)’ to ‘int (*)(t_k_cext *, ...)’ {aka ‘int (*)(struct k_cext *, ...)’} [-Wcast-function-type]
       k_cext_intfuncpointers[lokke]=(k_cext_f_int_callback)x->k_cext_process;
                                     ^
k_cext_funchandler.c: In function ‘k_cext_addfloatfunc’:
k_cext_funchandler.c:82:39: warning: cast between incompatible function types from ‘void (*)(struct k_cext *)’ to ‘float (*)(t_k_cext *, ...)’ {aka ‘float (*)(struct k_cext *, ...)’} [-Wcast-function-type]
       k_cext_floatfuncpointers[lokke]=(k_cext_f_float_callback)x->k_cext_process;
                                       ^
k_cext.c: In function ‘k_cextandfunc_new’:
k_cext.c:253:12: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
   sprintf(k.name,"%s.o",k.name);
           ~^~~~~        ~~~~~~
k_cext.c: In function ‘k_cext_setup’:
k_cext.c:314:46: warning: cast between incompatible function types from ‘void * (*)(t_symbol *, t_int,  t_atom *)’ {aka ‘void * (*)(struct _symbol *, long int,  struct _atom *)’} to ‘void * (*)(void)’ [-Wcast-function-type]
   k_cext_class = class_new(gensym("k_cext"), (t_newmethod)k_cext_new,
                                              ^
k_cext.c:322:48: warning: cast between incompatible function types from ‘void * (*)(t_symbol *, t_int,  t_atom *)’ {aka ‘void * (*)(struct _symbol *, long int,  struct _atom *)’} to ‘void * (*)(void)’ [-Wcast-function-type]
   k_cfunc_class = class_new(gensym("k_cfunc"), (t_newmethod)k_cfunc_new,
                                                ^
k_cext.c: In function ‘k_cext_print’:
k_cext.c:78:24: warning: ‘%s’ directive writing up to 499 bytes into a region of size between 489 and 496 [-Wformat-overflow=]
     sprintf(temp2,"%3d %s",lokke,temp);
                        ^~        ~~~~
k_cext.c:78:5: note: ‘sprintf’ output between 5 and 511 bytes into a destination of size 500
     sprintf(temp2,"%3d %s",lokke,temp);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from k_cext.c:196:
k_cext.c: In function ‘k_cextandfunc_new.constprop’:
k_cext_generatecode.c:268:25: warning: ‘%s’ directive writing up to 499 bytes into a region of size between 1 and 500 [-Wformat-overflow=]
        sprintf(temp2,"%s%s",orgind,string);
                         ^~         ~~~~~~
k_cext_generatecode.c:268:8: note: ‘sprintf’ output between 1 and 999 bytes into a destination of size 500
        sprintf(temp2,"%s%s",orgind,string);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_cext.c:253:21: warning: ‘.o’ directive writing 2 bytes into a region of size between 1 and 500 [-Wformat-overflow=]
   sprintf(k.name,"%s.o",k.name);
                     ^~
k_cext.c:253:3: note: ‘sprintf’ output between 3 and 502 bytes into a destination of size 500
   sprintf(k.name,"%s.o",k.name);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -DPD -DUNIX -DICECAST -O2 -funroll-loops -fomit-frame-pointer -Wall -W -Wno-shadow -Wstrict-prototypes -Wno-unused -Wno-parentheses -Wno-switch -fPIC  -I../../src -DINCLUDEPATH=\""`pwd`"\" -DLINUXINCLUDE=\""../../src"\" -o k_cext_unix.o -c k_cext_unix.c
cc -shared -o k_cext.pd_linux k_cext.o k_cext_unix.o -lc -lm -fPIC
/usr/bin/ld: k_cext_unix.o: in function `k_sys_mktempfilename':
k_cext_unix.c:(.text+0xcc): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
strip --strip-unneeded k_cext.pd_linux
rm -f k_cext.o ../k_cext.pd_linux
ln -s k_cext/k_cext.pd_linux ..
ln -sf k_cext/k_cext.pd_linux ../k_cfunc.pd_linux
`

I ran your tests with the following:

`ldd -r /tmp/pd-k_cext-G6UArD.c
	not a dynamic executable
`
and

` gcc -Wall -O2 /tmp/pd-k_cext-G6UArD.c -o /tmp/pd-k_cext-d3ipCR.c.o -shared -fPIC
/tmp/pd-k_cext-G6UArD.c:1:10: fatal error: /home/jrsv/Documents/Pd/externals/k_cext/../../src/m_pd.h: No such file or directory
 #include "/home/jrsv/Documents/Pd/externals/k_cext/../../src/m_pd.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by kmatheussen** [comment]
Did you move the external after compilation?
Anyway, you see the error, /home/jrsv/Documents/Pd/externals/k_cext/../../src/m_pd.h doesn't exist.

**Comment by JRSV** [comment]
the object is in my external folder,  and yes, I catched that message, but if it didnt find it (m_pd.h) how did it compile?
where should m_pd.h be? should I put a copy of that file with the *.pd_linux?

**Comment by kmatheussen** [comment]
m_pd.h is in the source code of pure data. You couldn't compile the k_cext external itself without that file, and when you compiled k_cext, the file /home/jrsv/Documents/Pd/externals/k_cext/../../src/m_pd.h must have existed. You can't delete or move the source code of k_cext.

**Comment by JRSV** [comment]
well.. its referencing a folder that does not exist, the k_cext external does not have a src folder. I have now compiled the object again with the m_pd.h in the same folder as the source and it still doesn't work.

**Comment by kmatheussen** [comment]
Yes, it's referring to a directory that doesn't exist, so you have to fix that. I guess the problem here is that you have m_pd.h in a standard include directory, and that's why you were able to compile k_cext itself.
Anyway, you can fix this by either unpacking the k_cext source code inside the "externals" directory in the pd source ode, or set the LINUXINCLUDEPATH variable in the Makefile. Closing issue.
